import { createClient } from '@/lib/supabase/server'
import { NextResponse } from 'next/server'

// GET /api/guru/ujian - List all ujian owned by current guru
export async function GET(request: Request) {
  try {
    const supabase = await createClient()

    // Get current user
    const { data: { user } } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json(
        { success: false, error: { code: 'UNAUTHORIZED', message: 'Tidak terautentikasi' } },
        { status: 401 }
      )
    }

    // Get query params
    const { searchParams } = new URL(request.url)
    const status = searchParams.get('status')

    // Build query
    let query = supabase
      .from('ujian')
      .select(`
        id,
        kode_ujian,
        judul,
        durasi,
        jumlah_opsi,
        status,
        show_result,
        created_at,
        ujian_kelas!inner(kelas_id, kelas:kelas(nama_kelas)),
        soal_count:soal(count)
      `)
      .eq('created_by', user.id)

    // Filter by status if provided
    if (status && (status === 'aktif' || status === 'nonaktif')) {
      query = query.eq('status', status)
    }

    const { data: ujianList, error } = await query.order('created_at', { ascending: false })

    if (error) {
      console.error('Error fetching ujian:', error)
      return NextResponse.json(
        { success: false, error: { code: 'SERVER_ERROR', message: 'Gagal mengambil data ujian' } },
        { status: 500 }
      )
    }

    // Transform data
    const formattedUjian = ujianList.map((u: any) => {
      // Extract unique kelas from ujian_kelas
      const kelasMap = new Map()
      u.ujian_kelas?.forEach((uk: any) => {
        if (uk.kelas) {
          kelasMap.set(uk.kelas_id, {
            id: uk.kelas_id,
            nama_kelas: uk.kelas.nama_kelas
          })
        }
      })

      return {
        id: u.id,
        kode_ujian: u.kode_ujian,
        judul: u.judul,
        durasi: u.durasi,
        jumlah_opsi: u.jumlah_opsi,
        status: u.status,
        show_result: u.show_result,
        created_at: u.created_at,
        kelas: Array.from(kelasMap.values()),
        jumlah_soal: u.soal_count?.[0]?.count || 0
      }
    })

    return NextResponse.json({
      success: true,
      data: {
        ujian: formattedUjian
      }
    })

  } catch (error) {
    console.error('Get ujian error:', error)
    return NextResponse.json(
      { success: false, error: { code: 'SERVER_ERROR', message: 'Terjadi kesalahan pada server' } },
      { status: 500 }
    )
  }
}

// POST /api/guru/ujian - Create new ujian
export async function POST(request: Request) {
  try {
    const supabase = await createClient()

    // Get current user
    const { data: { user } } = await supabase.auth.getUser()

    if (!user) {
      return NextResponse.json(
        { success: false, error: { code: 'UNAUTHORIZED', message: 'Tidak terautentikasi' } },
        { status: 401 }
      )
    }

    // Parse request body
    const body = await request.json()

    // Validation
    if (!body.judul || typeof body.judul !== 'string' || !body.judul.trim()) {
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'Judul ujian harus diisi' } },
        { status: 400 }
      )
    }

    if (!body.durasi || typeof body.durasi !== 'number' || body.durasi < 1) {
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'Durasi ujian harus minimal 1 menit' } },
        { status: 400 }
      )
    }

    if (!body.jumlah_opsi || (body.jumlah_opsi !== 4 && body.jumlah_opsi !== 5)) {
      return NextResponse.json(
        { success: false, error: { code: 'VALIDATION_ERROR', message: 'Jumlah opsi harus 4 atau 5' } },
        { status: 400 }
      )
    }

    const { judul, durasi, jumlah_opsi, show_result = true, kelas_ids = [] } = body

    // Insert new ujian (kode_ujian will be auto-generated by trigger)
    const { data: newUjian, error: ujianError } = await supabase
      .from('ujian')
      .insert({
        judul: judul.trim(),
        durasi,
        jumlah_opsi,
        show_result,
        created_by: user.id
      })
      .select('id, kode_ujian, judul, durasi, jumlah_opsi, status, show_result, created_at')
      .single()

    if (ujianError) {
      console.error('Error creating ujian:', ujianError)
      return NextResponse.json(
        { success: false, error: { code: 'SERVER_ERROR', message: 'Gagal membuat ujian' } },
        { status: 500 }
      )
    }

    // Insert kelas assignments if provided
    if (kelas_ids && kelas_ids.length > 0) {
      const kelasData = kelas_ids.map((kelasId: string) => ({
        ujian_id: newUjian.id,
        kelas_id: kelasId
      }))

      const { error: kelasError } = await supabase
        .from('ujian_kelas')
        .insert(kelasData)

      if (kelasError) {
        console.error('Error assigning kelas:', kelasError)
        // Continue anyway - ujian was created successfully
      }
    }

    return NextResponse.json({
      success: true,
      data: {
        id: newUjian.id,
        kode_ujian: newUjian.kode_ujian,
        judul: newUjian.judul,
        durasi: newUjian.durasi,
        jumlah_opsi: newUjian.jumlah_opsi,
        status: newUjian.status,
        show_result: newUjian.show_result,
        created_at: newUjian.created_at
      }
    })

  } catch (error) {
    console.error('Create ujian error:', error)
    return NextResponse.json(
      { success: false, error: { code: 'SERVER_ERROR', message: 'Terjadi kesalahan pada server' } },
      { status: 500 }
    )
  }
}
